services:
  front:
    build:
      context: .
    container_name: "react-portal-front"
    ports: 
      - "5173:5173"
    volumes:
      - ./app/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    