services:
  front:
    build: .
    ports: 
      - "5173:5173"
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./app
          target: app
          ignore:
            - node_modeles/
        - action: rebuild
          path: package.json
    