name: Code Check

on:
  push:

permissions:
  id-token: write
  contents: read

env:
  # GitHubActionsOIDCRole：作成したIAMロール名
  AWS_ROLE_ARN: arn:aws:iam::011077020616:role/oidc-test-role

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      # チェックアウトするアクション
      - name: Checkout Code
        uses: actions/checkout@v2
      # 特定バージョンのnodeを設定するアクション
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 24
      # dependencyのキャッシュ
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          #キャッシュしたファイルとキーを格納する場所(OSによって異なる)
          path: ~/.npm
          #キャッシュのリストアや保存をするためのキー
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          #キャッシュをリストアするためのキーのリスト
          restore-keys: |
            ${{ runner.os }}-node-
      # dependencyのインストール
      - run: npm ci
      # lint実行
      - run: npm run lint
